name: Checks

on:
  push:
    paths: ["src/**", ".github/workflows/lint-check.yml"]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  formatting-checks:
    name: Check linting (es-lint), formatting (prettier)
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: oven-sh/setup-bun@v2

      - name: Make dummy env for types
        run: |
          echo "ls -a ."
          ls -a .
          mv .env.example .env

      - name: Check linting and formatting
        run: bun run lint
